title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to uBlue (Alpha)"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.
  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome, Traveler!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features. This step will therefore remove all basic Fedora Flatpaks from your system! We will instead switch all core Flatpak applications over to the vastly superior, unfiltered Flathub. If you don't want to do this, simply exit this installer.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
  # check-user-flathub:
  #   source: yafti.screen.consent
  #   values:
  #     title: Missing Flathub Repository (User)
  #     condition:
  #       run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
  #     description: |
  #       We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
  #     actions:
  #       - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        Core:
          description: OS Applications
          default: true
          packages:
            - Backup: org.gnome.World.PikaBackup
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Characters: org.gnome.Characters
            - Connections: org.gnome.Connections
            - Contacts: org.gnome.Contacts
            - Document Viewer: org.gnome.Evince
            - Extensions Manager: com.mattjakeman.ExtensionManager
            - USB Flasher: com.system76.Popsicle
            - Mozilla Firefox: org.mozilla.firefox
            - Flatseal Permissions Manager: com.github.tchx84.Flatseal
            - Logs: org.gnome.Logs
            - Nautilus Preview: org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Weather: org.gnome.Weather
            - Disk Usage Analyzer: org.gnome.baobab
            - Clocks: org.gnome.clocks
            - Picture Viewer: org.gnome.Loupe
            - Font Viewer: org.gnome.font-viewer
            - Font Downloader: org.gustavoperedo.FontDownloader
            - Video Player: io.github.celluloid_player.Celluloid
        Gaming:
          description: "This is gonna be weirder than usual."
          default: false
          packages:
            - Discord: com.discordapp.Discord
            - MangoHUD: org.freedesktop.Platform.VulkanLayer.MangoHud
            - Steam: com.valvesoftware.Steam
            - Gamescope for Steam: com.valvesoftware.Steam.Utility.gamescope
            - Proton Updater for Steam: com.vysp3r.ProtonPlus
        Office:
          description: 🤓
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - Obsidian: md.obsidian.Obsidian
            - Logseq: com.logseq.Logseq
        Streaming:
          description: "Gonna be a VTuber someday."
          default: false
          packages:
            - OBS Studio: com.obsproject.Studio
            - VkCapture for OBS: com.obsproject.Studio.OBSVkCapture
            - Gstreamer for OBS: com.obsproject.Studio.Plugin.Gstreamer
            - Gstreamer VAAPI for OBS: com.obsproject.Studio.Plugin.GStreamerVaapi
        Misc:
          description: The rest of the owl.
          default: false
          packages:
            - Lollypop: org.gnome.Lollypop
            - Discord: com.discordapp.Discord
            - Epic Asset Manager: io.github.achetagames.epic_asset_manager

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying uBlue, we hope you enjoy it!